### ISSUE TITLE
Refactor code

### ISSUE THREAD

**Issue by pmareke** [Bimo99B9/autoUniCalendar#1]
Great job @Bimo99B9!

Taking a look to your code I think you can improve a lot the performance as, for example, you're iterating 3 times over the same [request](https://github.com/Bimo99B9/autoUniCalendar/blob/main/autoUniCalendar.py#L40).

With this change your script could speed up 3 times.

Also you're using some magic numbers like [here](https://github.com/Bimo99B9/autoUniCalendar/blob/main/autoUniCalendar.py#L52) or [here](https://github.com/Bimo99B9/autoUniCalendar/blob/main/autoUniCalendar.py#L61).

As I said before, great job and better utility! If you need some help just tell me!

**Comment by Bimo99B9** [comment]
Good morning @pmareke, first of all, thank you for reading the code and for telling me what you have seen that can be improved.

While I was writing the script, I realized that I could iterate just one time in the search algorithm, but as the server response is previously saved in the variable first_request, the script does not have to make the HTTP GET request 3 times, and the execution speed is not really affected.

Despite this, I am aware that the code would be more efficient with a single loop, but I am just a first year student and it was easier for me to do it that way. I will do research on it and try to make the code simpler and valid for future courses.

About magic numbers, do you mean declaring them in a variable instead of using the number?

Thank you so much.

**Comment by pmareke** [comment]
Hi @Bimo99B9 sorry if my message sounds impertinent ahaha I was trying to congratulate you because this is amazing!

Regarding the 3 `for-loop`, the problem is not the request itself, is the logic of each loop. If the request has 1 million lines you're going to read 3 million when you can just do it all the parse logic in the same loop.

The code is great and please don't think the opposite, I would love to have the same knowledge at your age!

When I referred to the magic numbers I meant that for example here `st = tmp.split(' ')[12]`, you're using `12` and I'm quite sure that you know why is 12 and not 7 or 8. But if a few months later someone (even yourself) use this code they will not understand this number.

The best approach is use a constant like:

```
ST_POSITON = 12
st = tmp.split(' ')[ST_POSITION]
```

And the same for the rest of indices in the script.

Finally I love to see that you're programming in English, which is awesome! The only thing is that some variables are quite difficult to understand their meaning, like `st, tmp, tmp2, f, g` and another ones are in Spanish (try to be consistent!)

One more time, THIS SCRIPT IS FUCKING AWESOME. If you have doubts about resources, programming or another topic please don't hesitate to reach me out ok?

If you want I can create a Pull Request here with some changes, just tell me and I will love to help.

**Comment by Bimo99B9** [comment]
Hi, your message certainly does not sound impertinent! I I now understand what you mean with the magic numbers and I completely agree with you., it is a really difficult code to understand since it is not even commented.

About the 3 `for-loop`, the problem is that each loop stops searching with a `break` when the wanted content is found, because there are more than one possible coincidences in the HTTP response, and not all of them are valid, and I don't really know how to make a search algorithm that stops searching for each variable when it finds each one (without the `break` the variable would be overwritten), so it would be very nice of you to create the pull request if you want.

I also agree with the problem of the variable names, I know it and I would like to correct it as the magic numbers problem, both caused because this script was done in a morning and I didn't care a lot about these things.

In the future, I'd like to add changes to make the script easier to use, catch the exceptions, and add features like to be able to choose the dates of the calendar to download, so I will try to make it better!

One last thing, I always program in English, but again, as I did this script really fast, some variables kept the name that Outlook used in its CSV file, so I will also change that.

To finish, thank you so much for your feedback, I really appreciate it and learn a lot with a code review like yours.
